// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS9fWCAvZDDTyIdvqNPdfXzMZqb_a556s',
    appId: '1:825628168434:web:233708c26da527fb0d006b',
    messagingSenderId: '825628168434',
    projectId: 'web-view-e99cc',
    authDomain: 'web-view-e99cc.firebaseapp.com',
    storageBucket: 'web-view-e99cc.appspot.com',
    measurementId: 'G-Q1KTV4W672',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3hdX7zeekWsT1ZWR0Rk_IvnVaiyNQ_TE',
    appId: '1:825628168434:android:622f2c702c2181580d006b',
    messagingSenderId: '825628168434',
    projectId: 'web-view-e99cc',
    storageBucket: 'web-view-e99cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCb2pco2-QBjCclVQQvfrPZJdR6r2zuDFQ',
    appId: '1:825628168434:ios:bc50fa71ef6259990d006b',
    messagingSenderId: '825628168434',
    projectId: 'web-view-e99cc',
    storageBucket: 'web-view-e99cc.appspot.com',
    iosClientId: '825628168434-ammlmq1p35kcoutvd02t85ifnun680cs.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterPrime',
  );
}
